### ISSUE TITLE
URL Link to the WorkItem

### ISSUE THREAD

**Issue by AlfonsZiegler** [jazz-community/printable-workitems#1]
Thank you for this very powerful widget. 

How it is possible to create a URL link to the visible workitem in the widget?

The URL links in tables work well.
The URL links to a specific children, or to the parent, or to any other linked workitem, work fine.

What I need is a clickable ID or a clickable Summary as URL link to open the workitem.

Attached to this issue you find some json-config-files:
[Printable_WorkItems_Configs.zip](https://github.com/jazz-community/printable-workitems/files/4142767/Printable_WorkItems_Configs.zip)

**Additional questions / requirements**

1) How is it possible to display the workitemtype image in a easy way?
- see also question/requirement 2) and 3)

2) How is it possible to search in process attachments?
- not working idea: {{processattachment#?[t:image;s:1;desc:Some Image;width:auto;height:auto;src_by_name:*story*;src_by_node:comment;src_by_result:url;]}}

3) How is it possible to search with dynamic text and wildcards?
- not working idea: {{processattachment#?[t:image;s:1;desc:Some Image;width:auto;height:auto;src_by_name:*{{workitemtype}}*;src_by_node:comment;src_by_result:url;]}}

**Comment by MartinBenninger** [comment]
This issue was linked by [RTC Work Item 964513](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/964513) on behalf of martin.benninger.ext@siemens.com

**Comment by AlfonsZiegler** [comment]
Thank you for creating the  [RTC Work Item 964513](https://bt-clmserver01.hqs.sbt.siemens.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/964513)

This is not transparent for me because I don't yet have access to the Siemens backlog. Please place major results in this chat, thanks!

**Comment by MartinBenninger** [comment]
@AlfonsZiegler The work item is just for our internal tracking. We will post the answers to your questions here on GitHub.

**Comment by dave007700** [comment]
@AlfonsZiegler 

I hope the following can answer your questions. Please note that this answers are for the Widget **v1.0.1** . This **might not be right** anymore for any newer version. All the answers are based of the **content** of the **"not working idea"** provided by you.

1) **How is it possible to display the workitemtype image in a easy way?**

* This is with the current **version (v1.0.1)** of the Widget **not achievable** with only Commands or Keywords. If you need it immediately there is a workaround, which isn't very elegant, by using HTML.

	`<a href="/'Jazz-Context'/resource/itemName/com.ibm.team.workitem.WorkItem/{{id}}" target="_blank" rel="noopener noreferrer">Link Text for {{id}}</a>`

	* You need to replace `'Jazz-Context'` with the context of Jazz in order for the above link to work. You can find the context by looking at your current URL in the Browser-Bar. It's the  value **between** the *Domain* and `"/web/..."`

<br>

2)  **How is it possible to search in process attachments?**

* The Keyword `processattachment` isn't known by Jazz by default and therefor I think that this is one of the problems causing it.

	* It's important to know, that the System will only apply Smart-Command's if the **Keyword exists**. 

	* You can check the list of all the available Keyword's for the current WorkItem by clicking  on the button *"Toggle Keys and Values"* inside the editor. 

	* I would recommend using either `attachment` or `id` as the Keyword.

	* [Wiki - Keywords](https://github.com/jazz-community/printable-workitems/wiki/Configuration#keywords)

* A second problem I see it that the value for `src_by_name` is set to "story". This means that the system should search for any attachment which has exactly the name *"story"*.

	* In order to check if the attachment contains the word "story" you need to asterisk it. Ex: `*story*` 
	
	* [Wiki - Image](https://github.com/jazz-community/printable-workitems/wiki/Configuration#image) 

<br>

3) **How is it possible to search with dynamic text and wildcards?**

* This **isn't possible** with the current **version (v1.0.1)** of this Widget.

**Comment by AlfonsZiegler** [comment]
@MartinBenninger & @dave007700 

Thank you for the detailed answers. Hopefully I have not restricted too much with my "not working idea".

**1) How is it possible to display the workitemtype image in a easy way?**
- Your answer is the solution for my question **How it is possible to create a URL link to the visible workitem in the widget?** Thanks! Your workaround works well.
- I take note that **display workitemtype image in a easy way** are not supported in the current version (v1.0.1).

**2) How it is possible to search in process attachment?**
- I am aware that I can only use known keywords. With *processattachment* I only wanted to formulate my need.
- The wildcards around story were suppressed in the comment, story was only written in bold.
- I take note that this is not supported in the current version (v1.0.1).

**3) How is it possible to search with dynamic text and wildcards?**
- I take note that this is not supported in the current version (v1.0.1).

Attached to this comment you find some updated json-config-files:
[Printable_WorkItems_Configs.zip](https://github.com/jazz-community/printable-workitems/files/4153354/Printable_WorkItems_Configs.zip)
